# Generated by Django 5.2.4 on 2025-07-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articulo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='imagen',
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen_intermedia',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/'),
        ),
    ]
