# Generated by Django 5.2.4 on 2025-08-05 19:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_articulo_imagen_articulo_imagen_intermedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen_intermedia',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.ruta_imagen_articulo),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.ruta_imagen_articulo),
        ),
    ]
